version: '3.8'

services:
  app:
    image: dockerish
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo_app?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
  
  db:
    image: mysql:8.0.3
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
      MYSQL_USER: root
      MYSQL_PASSWORD: root






# version: '3'
# services:
#   dbservice:
#     image: mysql:8.3.0
#     environment:
#       - MYSQL_ROOT_PASSWORD=root
  
#     volumes: 
#       - ./data:/var/lib/mysql
#     ports:
#       - 3308:3306
#     networks:
#       - Dockerone
    
#   appservice:
#     build: ./Dockerone
#     depends_on:
#       - dbservice
#     environment:
#       - spring.datasource.url=jdbc:mysql://dbservice:3306/todo_app?autoReconnect=true&useSSL=false
#       - spring.datasource.username=root
#       - spring.datasource.password=root
#     ports:
#       - 8091:9292

#     networks:
#       - Dockerone

# networks:
#   Dockerone:

